builders:
  json_generator:
    import: "package:duchow_json/builder.dart"
    builder_factories: ["jsonBuilder"]
    build_extensions: {".dart": ["json.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
